name = "maple-ledger"
compatibility_date = "2024-05-29"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "maple-ledger"
database_id = "b81b1df3-7f03-432f-b09b-4ad377fc5b0e"
